[package]
name = "encodedlua/project-name"
description = ""
license = "Apache-2.0"
authors = ["EncodedLua"]
version = "0.0.1"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
